- name: heisenbridge create venv
  include_tasks:
    file: venv_python.yml
    apply:
      tags:
        - matrix_venv_python
        - matrix_venv_python_heisenbridge
  vars:
    base_path: /opt/heisenbridge
    user: heisenbridge
    packages:
      - 'heisenbridge{% if matrix_heisenbridge_version %}=={{ matrix_heisenbridge_version }}{% endif %}'
  tags:
    - matrix_venv_python
    - matrix_venv_python_heisenbridge

- name: heisenbridge create systemd unit
  template:
    src: heisenbridge/systemd.service.j2
    dest: /etc/systemd/system/heisenbridge.service
    owner: root
    group: root
    mode: '0644'

- name: "heisenbridge {{ matrix_services_enabled | ternary('enable', 'disable') }} and {{ matrix_services_enabled | ternary('start', 'stop') }} systemd unit"
  systemd:
    name: heisenbridge.service
    daemon_reload: True
    enabled: '{{ matrix_services_enabled }}'
    state: "{{ matrix_services_enabled | ternary('started', 'stopped') }}"
