#- name: ma1sd install package
#  package:
#    name: ma1sd

- name: ma1sd create config
  template:
    src: ma1sd/config.yaml.j2
    dest: /etc/ma1sd/ma1sd.yaml
    owner: ma1sd
    group: ma1sd
    mode: '0640'

- name: ma1sd create systemd service override directory
  file:
    path: /etc/systemd/system/ma1sd.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: ma1sd override systemd service
  template:
    src: ma1sd/systemd.service.override.conf.j2
    dest: /etc/systemd/system/ma1sd.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: "ma1sd {{ matrix_services_enabled | ternary('enable', 'disable') }} and {{ matrix_services_enabled | ternary('start', 'stop') }} systemd unit"
  systemd:
    name: ma1sd
    enabled: '{{ matrix_services_enabled }}'
    state: "{{ matrix_services_enabled | ternary('started', 'stopped') }}"
