- name: tags-block
  tags: matrix
  when: role_matrix
  block:

    - name: import tasks from dependencies.yml
      import_tasks: dependencies.yml
      tags: matrix_dependencies
      when: import_matrix_dependencies

    - name: import tasks from users.yml
      import_tasks: users.yml
      tags: matrix_users
      when: import_matrix_users

    - name: import tasks from synapse.yml
      import_tasks: synapse.yml
      tags: matrix_synapse
      when: import_matrix_synapse

    - name: import tasks from synadm.yml
      import_tasks: synadm.yml
      tags: matrix_synadm
      when: import_matrix_synadm

    - name: import tasks from media_repo.yml
      import_tasks: media_repo.yml
      tags: matrix_media_repo
      when: import_matrix_media_repo

    - name: import tasks from ma1sd.yml
      import_tasks: ma1sd.yml
      tags: matrix_ma1sd
      when: import_matrix_ma1sd

    - name: import tasks from maubot.yml
      import_tasks: maubot.yml
      tags: matrix_maubot
      when: import_matrix_maubot

    - name: import tasks from reminder_bot.yml
      import_tasks: reminder_bot.yml
      tags: matrix_reminder_bot
      when: import_matrix_reminder_bot

    - name: import tasks from webhook.yml
      import_tasks: webhook.yml
      tags: matrix_webhook
      when: import_matrix_webhook
