- name: maubot create directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - path: /opt/maubot
    - path: /var/opt/maubot
    - path: /var/log/maubot
    - path: /etc/opt/maubot
      group: maubot
      mode: '0775'
  tags:
    - matrix_venv_python
    - matrix_venv_python_maubot

- name: maubot create venv
  include_tasks:
    file: venv_python.yml
    apply:
      tags:
        - matrix_venv_python
        - matrix_venv_python_maubot
  vars:
    base_path: /opt/maubot
    packages: '{{ matrix_maubot_dependencies_default + matrix_maubot_dependencies_plugins }}'
  tags:
    - matrix_venv_python
    - matrix_venv_python_maubot

- name: maubot clone repo
  git:
    repo: https://github.com/maubot/maubot.git
    dest: /opt/maubot/git
    update: False
    #version: ''

- name: maubot set fact _matrix_maubot_instances
  set_fact:
    _matrix_maubot_instances: "{{ _matrix_maubot_instances + [_matrix_maubot_instances_defaults | combine(item, recursive=True)] }}"
  loop: '{{ matrix_maubot_instances }}'
  loop_control:
    label: '{{ item.name }}'

- name: maubot include instance
  include_tasks: maubot_instance.yml
  loop: "{{ _matrix_maubot_instances }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
