- name: install dependencies
  package:
    name:
      - libolm-dev
      - libolm3
    default_release: "{{ 'buster-backports' if ansible_distribution_release == 'buster' else ansible_distribution_release }}"

- name: create directories
  file:
    path: '{{ item.path }}'
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - path: /opt/reminder-bot
    - path: /var/opt/reminder-bot
      owner: reminder-bot
      group: reminder-bot
      mode: '0750'
    - path: /var/log/reminder-bot
      group: reminder-bot
      mode: '0775'
    - path: /etc/opt/reminder-bot
      group: reminder-bot
      mode: '0750'

- name: create venv
  include_tasks:
    file: venv_python.yml
  vars:
    base_path: /opt/reminder-bot
    packages:
      - matrix-reminder-bot
      - matrix-reminder-bot[postgres]

# TODO: create database

- name: create config
  template:
    src: reminder_bot/config.yaml.j2
    dest: /etc/opt/reminder-bot/config.yaml
    owner: root
    group: reminder-bot
    mode: '0640'

- name: create systemd service unit
  template:
    src: reminder_bot/systemd.service.j2
    dest: /etc/systemd/system/reminder-bot.service
    owner: root
    group: root
    mode: '0644'

- name: enable and start systemd service unit
  systemd:
    name: reminder-bot.service
    enabled: True
    state: started
