- name: install synapse dependencies
  package:
    name:
      - libpq5
      - libpq-dev
      - redis-server
      - redis-tools
      - build-essential
      - python3-dev
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - libxslt1-dev
      - libicu-dev
      - libxml2-dev
      - libjemalloc2

- name: create venv
  include_tasks:
    file: venv_python.yml
  vars:
    base_path: /opt/synapse
    packages:
      - matrix-synapse
      - matrix-synapse-ldap3
      - matrix-synapse[postgres]
      - matrix-synapse[redis]
      - lxml
      - netaddr

- name: create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/opt/synapse
    - /var/opt/synapse
    - /var/log/synapse

- name: create logrotate cronjob
  template:
    src: synapse/logrotate.j2
    dest: /etc/cron.daily/synapse-logs
    owner: root
    group: root
    mode: '0755'

- name: set fact _matrix_synapse_instances
  set_fact:
    _matrix_synapse_instances: "{{ _matrix_synapse_instances + [_matrix_synapse_instances_defaults | combine(item, recursive=True)] }}"
  loop: '{{ matrix_synapse_instances }}'
  loop_control:
    label: '{{ item.name }}'

- name: include synapse instance
  include_tasks: synapse_instance.yml
  loop: "{{ _matrix_synapse_instances }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
