- name: synapse install dependencies
  package:
    name:
      - redis-server
      - redis-tools
      - build-essential
      - python3-dev
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - libxslt1-dev
      - libicu-dev
      - libxml2-dev
      - libjemalloc2
  tags:
    - matrix_venv_python
    - matrix_venv_python_synapse

- name: synapse create venv
  include_tasks:
    file: venv_python.yml
    apply:
      tags:
        - matrix_venv_python
        - matrix_venv_python_synapse
  vars:
    base_path: /opt/synapse
    packages:
      - 'matrix-synapse{% if matrix_synapse_version %}=={{ matrix_synapse_version }}{% endif %}'
      - 'matrix-synapse[postgres]{% if matrix_synapse_version %}=={{ matrix_synapse_version }}{% endif %}'
      - 'matrix-synapse[redis]{% if matrix_synapse_version %}=={{ matrix_synapse_version }}{% endif %}'
      - matrix-synapse-ldap3
      - lxml
      - netaddr
      - git+https://github.com/t2bot/synapse-simple-antispam#egg=synapse-simple-antispam
  tags:
    - matrix_venv_python
    - matrix_venv_python_synapse

- name: synapse clone matrix-synapse-rest-password-provider repo
  git:
    repo: '{{ matrix_synapse_rest_auth_provider_git.repo }}'
    dest: /opt/matrix-synapse-rest-password-provider
    update: '{{ matrix_synapse_rest_auth_provider_git.update | bool }}'
    version: '{{ matrix_synapse_rest_auth_provider_git.commit | default(matrix_synapse_rest_auth_provider_git.branch) }}'
  when: matrix_synapse_rest_auth_provider_install
  tags:
    - matrix_synapse_rest_auth_provider
    - matrix_synapse_rest_auth_provider_install

- name: synapse deploy rest-auth-provider plugin
  copy:
    src: /opt/matrix-synapse-rest-password-provider/rest_auth_provider.py
    dest: /opt/synapse/env/lib/python{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}/site-packages/rest_auth_provider.py
    remote_src: True
    owner: root
    group: root
    mode: '0644'
  when: matrix_synapse_rest_auth_provider_install
  tags:
    - matrix_synapse_rest_auth_provider
    - matrix_synapse_rest_auth_provider_deploy

- name: synapse create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /etc/opt/synapse
    - /var/opt/synapse
    - /var/log/synapse

- name: synapse create logrotate cronjob
  template:
    src: synapse/logrotate.j2
    dest: /etc/cron.daily/synapse-logs
    owner: root
    group: root
    mode: '0755'

- name: synapse set fact _matrix_synapse_instances
  set_fact:
    _matrix_synapse_instances: "{{ _matrix_synapse_instances + [_matrix_synapse_instances_defaults | combine(item, recursive=True)] }}"
  loop: '{{ matrix_synapse_instances }}'
  loop_control:
    label: '{{ item.name }}'
  tags: matrix_synadm

- name: synapse include instance
  include_tasks: synapse_instance.yml
  loop: "{{ _matrix_synapse_instances }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
