- name: users create groups
  group:
    name: '{{ item.name }}'
  loop: '{{ matrix_groups }}'
  tags: matrix_venv_python

- name: users create system users
  user:
    name: '{{ item.name }}'
    home: '{{ item.home }}'
    shell: "{{ item.shell | default('/usr/sbin/nologin') }}"
    system: True
    create_home: False
    groups: "{{ item.groups | default('') }}"
  loop: '{{ matrix_system_users }}'
  tags: matrix_venv_python

- name: users create home directories
  file:
    path: '{{ item.home }}'
    state: directory
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: "{{ item.mode | default('0750') }}"
  loop: '{{ matrix_system_users }}'
  tags: matrix_venv_python

# TODO: create postgres users
