- name: webhook clone repo
  git:
    repo: https://gitlab.phys.ethz.ch/isgphys/webhook-to-matrix-hookshot.git
    dest: /opt/webhook/git
    update: False
  become: yes
  become_user: webhook
  tags: matrix_venv_python

# TODO: create config, remove from git

- name: webhook create venv
  include_tasks:
    file: venv_python.yml
    apply:
      tags: matrix_venv_python
  vars:
    base_path: /opt/webhook/git
    user: webhook
  tags: matrix_venv_python

- name: webhook create systemd unit
  template:
    src: webhook/systemd.service.j2
    dest: /etc/systemd/system/webhook.service
    owner: root
    group: root
    mode: '0644'

- name: "webhook {{ matrix_services_enabled | ternary('enable', 'disable') }} and {{ matrix_services_enabled | ternary('start', 'stop') }} systemd unit"
  systemd:
    name: webhook.service
    daemon_reload: True
    enabled: '{{ matrix_services_enabled }}'
    state: "{{ matrix_services_enabled | ternary('started', 'stopped') }}"
